package com.harsh.hospitalmanagement.enums;

public enum AuditEventType {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    PATIENT_BOOKED_APPOINTMENT,
    PATIENT_CANCELLED_APPOINTMENT,
    DOCTOR_CREATED_AVAILABILITY,
    DOCTOR_UPDATED_AVAILABILITY,
    ADMIN_CREATED_DOCTOR,
    ADMIN_UPDATED_DOCTOR
}
